### PR TITLE
iOS Keychain - Use accessiblity option for all operations and throw PlatformException for SecErrors

### LINKED ISSUE #524: .read() return null since iOS 16.3.X even with the correct KeychainAccessibility
Package version: 

`flutter_secure_storage: ^8.0.0`

Flutter:

```
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (vor 9 Wochen) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

```

I have the following code: 

```dart
  final _storage = const FlutterSecureStorage(
    aOptions: AndroidOptions(encryptedSharedPreferences: true),
    iOptions: IOSOptions(
      synchronizable: false,
      // https://support.apple.com/en-us/HT213407
      // https://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background
      accessibility: KeychainAccessibility.first_unlock,
    ),
  );
```

```
  @override
  Future<String?> getAccessToken() async {
    final token = await _storage.read(key: "my_access_token");

   // The token is null, when the app was locked and we try to receive the token!! 😭

     return null;
  }
```

Regarding this question, the mode looks correct, but I just receive a null token when the app was moved into the background (not terminated) and the user locks the device. 
https://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background

Thanks for the support.

### PR DESCRIPTION
**Pull request by bierbaumtim**
This PR fixes the issue that the accessiblity option was ignored for containtsKey and delete. Since all functions now require the conversion for the accessiblity option, I refactored that into a seperate function.

While working on this, I noticed that errors were not being propagated properly. So I improved the error propagation so that now errors will lead to a PlatformException. 

I also noticed that the implementation of containsKey could be optimized. Reading the value is not neccessary therefore I removed it and use the status to determine if the key is contained.

All changes currently apply to iOS only. Since the macOS implementation is almost identical, I could apply the fixes there too, but I can't test them because I don't have a Mac. What's your oppinion on that?

The work on this PR started as an attempt to fix #524. The changes does not fully fix the issue descripted in #524. To do fix them you need to wait until the function `applicationProtectedDataDidBecomeAvailable` is called and stop reading values when `applicationProtectedDataWillBecomeUnavailable` is called. I created a Gist containing the necessary code to do that.  https://gist.github.com/bierbaumtim/63c5057fc2889558d1801d95d93b6c6c
I think this plugin should support fetching and listening to changes in the availability of the keychain. But I want to know your opinion on that and if support should be added, should this be a seperate PR?

### CODE REVIEW

**Comment by bierbaumtim** [comment]
@juliansteenbakker Could you review the changes?

**Comment by juliansteenbakker** [comment]
Thank you for your work! Sorry for the late response, i'm planning on picking up some overdue work this plugin in the comming days. 

I think it will be good to add the same fixes on macOS. I can test them since i do have a mac. If you can create a separate PR for this, and for the new fetching and listening functions that would be great. Also, can you update this PR with the latest code base available?

**Comment by bierbaumtim** [comment]
Thanks for your feedback. I plan to work on it on Saturday.

**Comment by bierbaumtim** [comment]
PR is now update to date with latest code base

**Comment by bierbaumtim** [comment]
Could also fix #532, #519

**Pull request merged**
