### PR TITLE
[Windows] Write encrypted data to files instead of the windows credential system

### PR DESCRIPTION
**Pull request by Mino5531**
The data to store is encrypted with a key that is stored in the windows credential system and then written to a file in the app specific `%appdata%` folder. 
This fixes: #450, fixes: #361, fixes: #345

This should also be backwards compatible with old data stored in the windows credential system.

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
Thank you for your work. I need to dust of my windows laptop in order to check it, but afterwards ill let you know.

**Comment by juliansteenbakker** [comment]
I hope that someone else has a windows pc to test this on, because i have some problems firing up mine.

**Comment by cwangfr** [comment]
i have tested. it works.

**Comment by Eradparvar** [comment]
Thank you @juliansteenbakker  for doing a great job maintaining the package.  What are your thoughts about merging this into the default branch?

**Pull request merged**
