### PR TITLE
Rough windows implementation of secure storage

### LINKED ISSUE #242: WIndows support
Please add windows support for it

### PR DESCRIPTION
**Pull request by kennethnym**
This is a rough Windows implementation of `flutter_secure_storage`. The implementaion utilizes `wincred.h` APIs, particularly:
- `CredReadW`
- `CredWriteW`
- `CredDeleteW`

to read/write/delete encrypted values on Windows. The encrypted values are associated with the currently logged in user, and other users on the computer will not be able to access and read the encrypted values.

I am not an experienced C++ programmer, so I am 100% sure that my C++ code can be improved, but the code is ported over from my own Flutter projects and it has worked very well. One thing, however, is that I am not aware of any meaningful way to `readAll` and `deleteAll` encrypted values on Windows, since the functions mentioned above work on a per-item basis.

The code has been tested on Windows 11 and I have not experienced any issue.

closes #242 #222

### CODE REVIEW

**Comment by jhancock4d** [comment]
Does this cause any prompts for the user or does it work transparently?

**Comment by jhancock4d** [comment]
Looks like the example fails because read_all isn't implemented.  Could you implement please?

**Comment by jhancock4d** [comment]
Also note that I've broken this out in PR #257 as a separate plugin with the platform interface implemented. Depending on the maintainer's wishes you may want to just work from that PR to implement readAll and deleteAll (perhaps prefix all of the keys that are for this storage like I have done with web if you can't get just the ones for the current app?).

**Comment by kennethnym** [comment]
> Does this cause any prompts for the user or does it work transparently?
It does work silently with no prompts.

**Comment by kennethnym** [comment]
> Also note that I've broken this out in PR #257 as a separate plugin with the platform interface implemented. Depending on the maintainer's wishes you may want to just work from that PR to implement readAll and deleteAll (perhaps prefix all of the keys that are for this storage like I have done with web if you can't get just the ones for the current app?).

This is a good idea. I can implement that.

**Comment by juliansteenbakker** [comment]
Implemented in #257

**Comment by JohnGalt1717** [comment]
@juliansteenbakker This shouldn't be closed yet, as readAll and deleteAll isn't implemented. Hopefully @kennethnym can take the current develop branch now and do a pull request to add the 2 remaining methods.

**Comment by kennethnym** [comment]
will do

**Comment by juliansteenbakker** [comment]
>  Hopefully @kennethnym can take the current develop branch now and do a pull request to add the 2 remaining methods.

That is indeed the way to go since the creator of #257 added this code to his PR and i merged that.

**Pull request closed without merging**
