### PR TITLE
add testing mock

### PR DESCRIPTION
**Pull request by Goxiaoy**
add mock for testing purpose

### CODE REVIEW

**Comment by mogol** [comment]
Hi @Goxiaoy 
Why is mock implementation needed? doesn't [Mockito](https://pub.dartlang.org/packages/mockito) cover this case?

**Comment by Goxiaoy** [comment]
Because when I try to do unittest within codes rely on this package，error comes with no implementation on this platform, which means on my computer

**Comment by Goxiaoy** [comment]
And it is learned from package shared_preferences

**Comment by mogol** [comment]
Would it work in your case?

```dart

import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:mockito/mockito.dart';
import 'package:test/test.dart';

void main() {
  test('Sample mock', () async {
    final storage = MockStorage();
    when(storage.read(key: 'name')).thenAnswer((_) => Future.value('Stub'));

    final name = await storage.read(key: 'name');
    expect(name, 'Stub');
  });
}

class MockStorage extends Mock implements FlutterSecureStorage{}
```

**Comment by Goxiaoy** [comment]
It works for me. I am using dependency injection in my flutter project. so it's quite easy for me to replace FlutterSecureStorage to the mock class. But for those who did not, it's hard to replace it.

It's fine to close this PR. Thank you so much for your introduce of mockito.

**Comment by tirth-stasis** [comment]
> Would it work in your case?
> 
> ```dart
> import 'package:flutter_secure_storage/flutter_secure_storage.dart';
> import 'package:mockito/mockito.dart';
> import 'package:test/test.dart';
> 
> void main() {
>   test('Sample mock', () async {
>     final storage = MockStorage();
>     when(storage.read(key: 'name')).thenAnswer((_) => Future.value('Stub'));
> 
>     final name = await storage.read(key: 'name');
>     expect(name, 'Stub');
>   });
> }
> 
> class MockStorage extends Mock implements FlutterSecureStorage{}
> ```

How to do that for `write` method?

**Pull request closed without merging**
