### PR TITLE
Add melos to project

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Using `melos` makes it much easier to manage multi-module repos such as this.
In order to set everything up, run `melos bootstrap` in the root directory of this repo and the `pubspec_overrides.yaml` will automatically be generated.
Publishing new package versions is as easy as running `melos publish --no-dry-run` (without `--no-dry-run` it does just a dry run to see if publishing would go smoothly).
You might consider migrating to `melos` as it will also make your CI much more easy.

If you want me to complete this PR, just let me know and I will properly migrate the CI also.

### CODE REVIEW

**Comment by juliansteenbakker** [comment]
@ThexXTURBOXx This looks promising! I would be happy to integrate this. If its possible for you to complete the PR that would be great.

**Comment by ThexXTURBOXx** [comment]
@juliansteenbakker Thank you very much for your feedback! I have also migrated the CI and added some documentation about how to set up melos on a local machine - it is very quick to get it running.
I have not tested the CI yet - so there could be some issues. However, as soon as you allow the workflows to run on this PR, we will see if everything works properly!

**Comment by ThexXTURBOXx** [comment]
@juliansteenbakker Sorry, forgot to add the right paths to the $PATH. Now, it should work :)

**Comment by ThexXTURBOXx** [comment]
I am terribly sorry, I had another typo in the commands - now it should really work

**Comment by ThexXTURBOXx** [comment]
Perfect, now it worked fine! `F:\_Coding\flutter_secure_storage\flutter_secure_storage_windows\test\unit_test.dart` actually had bad formatting - so I fixed it. Now the formatting check will also pass.
This PR is now ready to get merged! :)

**Comment by ThexXTURBOXx** [comment]
By the way: `flutter drive` has problems: https://github.com/mogol/flutter_secure_storage/actions/runs/8983183839/job/24672407474?pr=681#step:7:79

According to [this SO](https://stackoverflow.com/a/74819011/5894824), you probably need to wait [for the GitHub-hosted ARM64 runners](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/). Or is it maybe enough to just specify `arch: arm64` or something?
Anyway, this is out of the scope of this PR, I would say... So, yes, feel free to merge this :)

**Comment by vicenterusso** [comment]
> By the way: `flutter drive` has problems: https://github.com/mogol/flutter_secure_storage/actions/runs/8983183839/job/24672407474?pr=681#step:7:79
> 
> According to [this SO](https://stackoverflow.com/a/74819011/5894824), you probably need to wait [for the GitHub-hosted ARM64 runners](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/). Or is it maybe enough to just specify `arch: arm64` or something? Anyway, this is out of the scope of this PR, I would say... So, yes, feel free to merge this :)

Isar was using macos runners for android integration tests. I changed to ubuntu-latest without problems. Maybe this could be done too?

**Comment by juliansteenbakker** [comment]
I have fixed this issue already on another branch, and will update this asap.

**Pull request merged**
