### PR TITLE
Android encryption migration

### LINKED ISSUE #161: Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
How to fix this problem? 

```
E/flutter (29195): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E/flutter (29195): 	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
E/flutter (29195): 	at com.android.org.conscrypt.OpenSSLCipher$EVP_CIPHER.doFinalInternal(OpenSSLCipher.java:570)
E/flutter (29195): 	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:351)
E/flutter (29195): 	at javax.crypto.Cipher.doFinal(Cipher.java:1741)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.decrypt(StorageCipher18Implementation.java:91)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.decodeRawValue(FlutterSecureStoragePlugin.java:163)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.read(FlutterSecureStoragePlugin.java:144)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.access$300(FlutterSecureStoragePlugin.java:29)
E/flutter (29195): 	at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin$MethodRunner.run(FlutterSecureStoragePlugin.java:197)
E/flutter (29195): 	at java.lang.Thread.run(Thread.java:764)
E/flutter (29195): , null)
```

### PR DESCRIPTION
**Pull request by juliansteenbakker**
This PR probably fixes #161, #248, #278, #312

This PR enables the migration of data to encryptedSharedPreference when enabled.
This PR also adds some other checks to ensure initialization performs correctly.

### CODE REVIEW

**Comment by justoke** [comment]
Hi. When would this change be available in the stable channel?

**Comment by juliansteenbakker** [comment]
This is already available in version 5.0.2

**Comment by justoke** [comment]
I've been running into the issue #248 where this exception is hit on release builds, and even after trying version 5.0.2 it still occurs. On Android you have to open the App settings and clear data and cache. Then restarting the app it will start up. On iOS there is no recovery and the app is unable to start - at least if you are trying to access secure storage.

Should I raise another issue on this?

```
D/FlutterSecureStoragePl(20913): Initializing StorageCipher
D/FlutterSecureStoragePl(20913): StorageCipher initialization complete
I/flutter (20913): PlatformException(Exception encountered, read, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
I/flutter (20913):      at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
I/flutter (20913):      at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
I/flutter (20913):      at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
I/flutter (20913):      at javax.crypto.Cipher.doFinal(Cipher.java:2055)
I/flutter (20913):      at b.c.a.g.b.b(Unknown Source:30)
I/flutter (20913):      at b.c.a.f.l(Unknown Source:11)
I/flutter (20913):      at b.c.a.f.r(Unknown Source:7)
I/flutter (20913):      at b.c.a.f.e(Unknown Source:0)
I/flutter (20913):      at b.c.a.e.run(Unknown Source:134)
I/flutter (20913):      at android.os.Handler.handleCallback(Handler.java:938)
I/flutter (20913):      at android.os.Handler.dispatchMessage(Handler.java:99)
I/flutter (20913):      at android.os.Looper.loop(Looper.java:246)
I/flutter (20913):      at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by juliansteenbakker** [comment]
If the exception is also occurring on iOS you should open a new ticket. I am not aware of this problem on iOS. For Android, are you using the following?:
```dart
  AndroidOptions _getAndroidOptions() => const AndroidOptions(
        encryptedSharedPreferences: true,
      );
```

**Comment by justoke** [comment]
I'm not using those options, please could you explain where this code should be placed and is this platform specific? Thank you.

**Comment by grafovdenis** [comment]
Hey, @justoke!
How did you fixed this out?

**Comment by justoke** [comment]
> Hey, @justoke! How did you fixed this out?
I resolved this by upgrading to the latest version, but also had to upgrade a third party dependency to use the latest 5.0.2 version. I see people having issues with earlier versions - like 4.2 on Android 11. I'd recommend upgrading to 5.0.2. This resolved all the issues I had.

**Pull request merged**
