### PR TITLE
Minor fix: prevent rtl bug fix from permanently changing locale

### PR DESCRIPTION
**Pull request by iassal**
Following up on the fix in  https://github.com/mogol/flutter_secure_storage/pull/132 

cc: @mogol @hmawla

### CODE REVIEW

**Comment by iassal** [comment]
Thanks Mogol, any plans for releasing soon? I can help with the release PR if needed

**Comment by iassal** [comment]
Thanks @mogol , any plans for releasing soon? I can help with the release PR if needed

**Comment by mogol** [comment]
@iassal I wanna to run smoke testing before releasing to make sure nothing is broken. ETA- end of this week

**Comment by walidbagh** [comment]
@mogol any news about releasing this ?

**Comment by iassal** [comment]
@mogol friendly ping

**Comment by mr-mamali** [comment]
Any news about realising this ?
+1

We are waiting ..🤞

**Comment by mogol** [comment]
I have just released, please try v3.3.4

**Comment by hmawla** [comment]
> I have just released, please try v3.3.4

Great to know, and great work man!

**Pull request merged**
